<a href="https://colab.research.google.com/github/cellrishi-code/pytorch-repo/blob/main/07_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
import math

In [11]:
a = torch.empty(2,3)

In [12]:
a   # initallied by the random value in the tensor

tensor([[3.6283e-37, 4.4238e-41, 5.6595e-19],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [13]:
c = torch.tensor([1,6,-67,-25])

In [14]:
c.abs()

tensor([ 1,  6, 67, 25])

In [15]:
## actual praticng of autograd module in pytorch

In [17]:
x = torch.tensor(3.0, requires_grad=True)

In [18]:
y = x**2

In [19]:
y.backward()

In [20]:
x.grad

tensor(6.)

In [27]:
x = torch.tensor(3.0, requires_grad=True)
y = torch.sin(x)
y.backward()
x.grad


tensor(-0.9900)

In [28]:
## simple neural newtrok building

In [29]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)  ## here in x , there is no required gard is true , we no need to find derivates wrt to x

In [30]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [31]:
z = w*x +b

In [32]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [33]:
y_pred = torch.sigmoid(z)

In [34]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [35]:

# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))



In [36]:
loss = binary_cross_entropy_loss(y_pred,y)

In [37]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [39]:
loss.backward()

In [42]:
## at once finding the derivates
w.grad


tensor(6.6918)

In [43]:
b.grad

tensor(0.9988)

In [44]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)

In [46]:
y = (x**2).mean()

In [47]:
y.backward()

In [48]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [49]:
## clearing grad

In [57]:
x = torch.tensor(2.0, requires_grad=True)

In [69]:
y =x**2   ## this is called forward pass

In [70]:
y.backward()

In [71]:
x.grad

tensor(4.)

In [73]:
x.grad.zero_()    ## here we are doing inplace 0 operation

tensor(0.)

In [74]:
## disable the gradient tracking in pytorch

1. require_grad_ ==> do it false
2.detach()
3.torch.no_grad()